### PR TITLE
ft_master/gsuite_custom_headers

### PR DESCRIPTION
**Pull request by sveinugu**

### CODE REVIEW

**Comment by sveinugu** [comment]
@dianadom I have now finished the GSuite update for custom header variables. It ended up being a large cleanup operation (as I did not know this was a blocker in the beginning), including code cleanup, synchronizing character handling in GSuite and GTrack, and properly implementing UniCode support. I was in the middle of this when I got message that is was a blocker, so it took a little while to finish, unfortunately. But here it is!

**Comment by sveinugu** [comment]
GSuite now has emoji support:

screen shot 2018-12-14 at 01 18 50

**Comment by sveinugu** [comment]
And for GTrack:
screen shot 2018-12-14 at 01 48 27

**Review by sandve — APPROVED** [review]
Based on some skim reading and look through commit messages this looks good to me!

**Pull request merged**
