### PR TITLE
bug_master/trello_iUaHUows

### PR DESCRIPTION
**Pull request by sveinugu**
Should now support analysis of a track against itself. Some updates to make disk memoization work and used (again) in tests. Fixed issues that came up in tests. Improved debugging.

### CODE REVIEW

**Comment by sveinugu** [comment]
@sandve Spent a very long time fixing the bugs, as I were unable to get to the exceptions causing them for two reasons:
1. VERBOSE did not log the exceptions (which was from Analysis.py and not from the statistic)
2. PASS_ON_VALIDSTAT_EXCEPTIONS raised only the first exception in each analysis category (when debugging from the old analysis tool), which was mostly trackformat exceptions or similar, that anyways should have been there.

So the real exception was hidden and I did not understand anything. Improved the debugging so that VERBOSE logs all exceptions, which would have made the exercise a whole lot easier. Hopefully debugging is starting to get a bit mature now, after 9 years..

**Comment by sveinugu** [comment]
@dianadom @borissim Same track vs itself now works. Required a bunch of core changes and took a lot of time. Awaiting review from @sandve before I will merge it into quick.

**Review by sandve — COMMENTED** [review]
Looks good!

The only thing I did not understand was how “restTracks” from line 154 of Analysis.py was used. I could not see any usage of it. Related to this, line 157 also looked strange to me - maybe add a comment in the code regarding this peculiarity?

Feel free to approve it yourself given that the above is okay!

And by the way, a very elegant “_runTypeGenerator” :)

**Review by sandve — APPROVED** [review]
Feel free to do the merging given that the point I mention in my previous comment is okay!

**Comment by sveinugu** [comment]
@sandve  I had to write some new logic anyway, and I found it a little hard to force myself to write new code for track and track2 now, and not allow for easy trackstructure extension.. However, as noted in the comment, we should think through if we still require that all unique tracks are touched by the statistic when doing trackstructure analyses, so I might have spent 20 minutes for nothing..

**Comment by sveinugu** [comment]
@sandve Ah, I see now that line 157 should use restTracks and not tracks. Strangely, PyCharm did not notice me that restTracks was not used. I will fix it and create a new pull request and merge it, if you now understand the code.

**Comment by sveinugu** [comment]
@sandve Nice catch! :-)

**Comment by sveinugu** [comment]
@sandve  in addition, line 157 is just stupid. Should have been 

set(_.getUniqueKey(self._genome) for _ in restTracks)

Exchanged the temporary variable 'track' with '_' (which is the pythonic best practice), but just in one place!

Code review is a nice thing! :-)

**Comment by sveinugu** [comment]
@sandve 

Or perhaps

set(tr.getUniqueKey(self._genome) for tr in restTracks)

is better for readability? ('track' cannot be used, as it is used in the for loop above)

**Comment by sandve** [comment]
I think the "tr" is best in this case, as it is indeed used.

And agree that code review is indeed nice! Is more interesting, more useful for getting an overview and takes less time than I would have anticipated! 
At least a very good thing when the reviewer is also interested in the code that is being reviewed.

**Comment by sveinugu** [comment]
Updated in https://github.com/hyperbrowser/genomic-hyperbrowser/pull/42

**Pull request closed without merging**
